### ISSUE TITLE
Create a New README.md file for Improved Contributions Guidelines.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#1]
The README.md file is just normal , You can Improve it by add website preview and contributions guidelines to it.

**Comment by Ujjwal-soni98** [comment]
Hey Kanishk, if we add steps for contribution to the contribution guidelines section , will it be appropriate??

**Comment by GJS2162** [comment]
**@Mr-Sunglasses I want to contribute to this. Could you assign this to me.**

**Comment by Mr-Sunglasses** [comment]
@GJS2162  - https://readme.so/ use this site for creating README.md

We want README.md like this https://github.com/SatyamX64/space_empires

**Comment by Mr-Sunglasses** [comment]
> Hey Kanishk, if we add steps for contribution to the contribution guidelines section , will it be appropriate??

So @Ujjwal-soni98 We want to make it beginner friendly So for now we are adding everything in README.md

**Comment by Mr-Sunglasses** [comment]
@GJS2162 I have accepted your PR for the contributions in README.md.

It is good that you can add the website preview in it.

**Comment by Mr-Sunglasses** [comment]
great work @GJS2162 , ✌🏻
