### ISSUE TITLE
Sidebar and links are broken on contact page in mobile view

### ISSUE THREAD

**Issue by codecShivam** [FOSS-Community/website-fossc#101]
When viewing the contact page on mobile devices and opening the sidebar, the entire sidebar appears to be broken. The links, as well as the sidebar itself, are not displayed properly, and the content is not accessible.

![fossc](https://user-images.githubusercontent.com/118369445/229952271-de5185f8-af3a-41c1-8882-c5f8de5b0198.jpeg)

**Comment by Mr-Sunglasses** [comment]
@codecShivam thanks for listing the bug we'll fix it as soon as possbile.

**Comment by Mr-Sunglasses** [comment]
![Screenshot 2023-04-06 at 5 00 27 AM](https://user-images.githubusercontent.com/81439109/230235189-97993c2c-b92d-4079-8b7e-4fc379485aa1.png)

It is working now [Contact form](https://fosscu.org/contact), @codecShivam thanks for raising the issue.

Frankly telling you 😅, it is an SOS 🆘 fix, I wrote very bad code, and will fix the badly written code Until the upcoming release.

TODO: break the contact page into components and pages.
