### ISSUE TITLE
Guide page is not responsive in mobile and tablet screens.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#102]
url : https://fosscu.org/guide
code url: https://github.com/FOSS-Community/website-fossc/blob/main/src/components/Guide_Element.jsx

# Ref for mobile screen

## Tested on ( device )

![Screenshot 2023-04-06 at 12 17 40 AM](https://user-images.githubusercontent.com/81439109/230177753-615c2cef-e1d0-4e82-8d28-2bf1db212544.png)

## Results

![Screenshot 2023-04-06 at 12 17 17 AM](https://user-images.githubusercontent.com/81439109/230177835-59344475-e086-4fab-9af5-83b5639c1545.png) ![Screenshot 2023-04-06 at 12 17 31 AM](https://user-images.githubusercontent.com/81439109/230177846-19426a0a-7756-4339-9dfe-28ee823efbdf.png)

# Ref on the tablet screen

## Tested on ( device )

![Screenshot 2023-04-06 at 12 18 19 AM](https://user-images.githubusercontent.com/81439109/230178198-80557b77-5a6c-4c89-8c07-06d4af717bd9.png)

## Results 

![Screenshot 2023-04-06 at 12 18 00 AM](https://user-images.githubusercontent.com/81439109/230178291-135bac11-5752-4b04-be85-9c21bff6971f.png)

**Comment by codecShivam** [comment]
I would like to contribute to it, sir could you please assign this task to me...

**Comment by Mr-Sunglasses** [comment]
#106 solves this issue. thx @codecShivam
