### ISSUE TITLE
README.md Still using create-react-app but website is migrated to VITE 💨

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#105]
In the website [README.md](https://github.com/FOSS-Community/website-fossc/blob/main/README.md?plain=1#:~:text=This%20project%20was%20bootstrapped%20with%20%5BCreate%20React%20App%5D(https%3A//github.com/facebook/create%2Dreact%2Dapp).) is still using `create-react-app` but the website is migrated `vite` so it is better to change it in [README.md](https://github.com/FOSS-Community/website-fossc/blob/main/README.md?plain=1#:~:text=This%20project%20was%20bootstrapped%20with%20%5BCreate%20React%20App%5D(https%3A//github.com/facebook/create%2Dreact%2Dapp).) to the latest standards of `vite` we are using

**Comment by codecShivam** [comment]
> @codecShivam can you do that

 I'm not entirely sure if i can do it, as I have some doubts about this. However, I'm happy to take a closer look and see if I can... Thanks for mentioning me sir :bow:

**Comment by Mr-Sunglasses** [comment]
![Fixed it](https://media1.giphy.com/media/k10R0bgUhNMtO/giphy.gif)
