### ISSUE TITLE
Adding diffrent social handle 

### ISSUE THREAD

**Issue by Bharadwajshivam28** [FOSS-Community/website-fossc#109]
@Mr-Sunglasses In the footer section there is different handles of fosscu including instagram, twitter and github.... We can add more like of linkedin and discord... If it is valueable then please assign it to me sir so i can go with it

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-10 01-32-55](https://user-images.githubusercontent.com/108119109/230794316-d63483bc-3082-49aa-aac2-b01124acd685.png)

**Comment by Mr-Sunglasses** [comment]
No we don't need it RN. We have already it in our contacts page.

**Comment by Bharadwajshivam28** [comment]
> No we don't need it RN. We have already it in our contacts page.

Ok
