### ISSUE TITLE
Add new members to the team.

### ISSUE THREAD

**Issue by akshatcoder-hash** [FOSS-Community/website-fossc#11]
Recently new members have been added to the community. Add their details on the teams page:
![image](https://user-images.githubusercontent.com/69577224/175806241-6c2eee4d-6dd4-408d-86a3-19d1cc17e54f.png)

**Comment by Prashant7451** [comment]
@akshatcoder-hash I want to work on this ..

**Comment by rohitroy-github** [comment]
Can I work on this issue ?

**Comment by GJS2162** [comment]
Hey @akshatcoder-hash  I want to work on this . Could you assign it to me ?

**Comment by akshatcoder-hash** [comment]
Assigned @GJS2162

**Comment by Mr-Sunglasses** [comment]
@akshatcoder-hash , @GJS2162 All of this is now upgraded.
