### ISSUE TITLE
privacy policy 

### ISSUE THREAD

**Issue by Bharadwajshivam28** [FOSS-Community/website-fossc#122]
Currently we not have privacy policy so we can create it or give a page displaying we are building it

![Screenshot from 2023-04-19 00-06-56](https://user-images.githubusercontent.com/108119109/232872230-4282ae41-b1af-4448-8b56-577760b285b7.png)

**Comment by Mr-Sunglasses** [comment]
@Bharadwajshivam28 Thx for the issue we'll make it.

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by tanishkkkaa** [comment]
hello sir @Mr-Sunglasses i would like to work on this issue

**Comment by akshatcoder-hash** [comment]
Here you go! @tanishkkkaa

**Comment by hiCXK** [comment]
Hello @Mr-Sunglasses sir! Do we have to add the privacy policy file in website-fossc repo (fosscu.org) or the community-hub repo (docs.fosscu.org) and then link it on the page of fosscu.org?

**Comment by draunger** [comment]
@Mr-Sunglasses I want to work on this

**Comment by Mr-Sunglasses** [comment]
Hey @draunger Sure you can work on this issue go ahead 🙂

**Comment by draunger** [comment]
> Hey @draunger Sure you can work on this issue go ahead 🙂

@Mr-Sunglasses can you explain me this issue clearly as I understand little bit of it

**Comment by draunger** [comment]
@Mr-Sunglasses ??

**Comment by codecShivam** [comment]
fixed in #190
