### ISSUE TITLE
for Updating Footer social Links 

### ISSUE THREAD

**Issue by Saurav-Pant** [FOSS-Community/website-fossc#125]
we can add a hovering effect on social links
(https://user-images.githubusercontent.com/103263909/233390042-0744047e-53df-4ece-b36d-2c7a670209a1.png)

**Comment by Saurav-Pant** [comment]
assign it to me, I want to work on it.

**Comment by anubhav1206** [comment]
Can i work on it?

**Comment by Saurav-Pant** [comment]
I added this hovering effect, how is this? @Mr-Sunglasses 
https://user-images.githubusercontent.com/103263909/233756889-a384b2fd-5cce-462a-b0f5-b3c35f017628.mp4

**Comment by Mr-Sunglasses** [comment]
@Saurav-Pant Looks nice

**Comment by Saurav-Pant** [comment]
#128, it is the PR.
