### ISSUE TITLE
for Distinguish between heading and links in the footer

### ISSUE THREAD

**Issue by Saurav-Pant** [FOSS-Community/website-fossc#126]
Here we can change the color of the heading so clearly see the distinction between the heading and links.
(https://user-images.githubusercontent.com/103263909/233391665-147adb8c-3eed-401c-924e-8aad950ba4f2.png)

**Comment by Saurav-Pant** [comment]
assign it to me, I want to work on it.

**Comment by Saurav-Pant** [comment]
I added green color, to clearly distinguish between the heading, it also does not lead to many colors in the footer because green is also previously present In the footer
(https://user-images.githubusercontent.com/103263909/233757144-76e35f33-6a1c-4130-ae4f-1e38d55ab0b2.png)

**Comment by Arpit-mohankar** [comment]
@Saurav-Pant is this issue opened?

**Comment by Saurav-Pant** [comment]
Yes, it is not merged yet
