### ISSUE TITLE
Readme Updation

### ISSUE THREAD

**Issue by Saurav-Pant** [FOSS-Community/website-fossc#127]
I noticed that some users who are not familiar with Yarn may encounter errors when trying to run the application. To help prevent this, I suggest updating the README to include the yarn install command before yarn start. This ensures that all necessary packages and dependencies are installed before running the application.
(https://user-images.githubusercontent.com/103263909/233758159-14c30519-7c9c-4417-9825-a9c4305983e9.png)

**Comment by vimal-oneway** [comment]
can i work on it

**Comment by Mr-Sunglasses** [comment]
@vimal-oneway Sure go ahead.

**Comment by Mr-Sunglasses** [comment]
#136
