### ISSUE TITLE
Add a resources page

### ISSUE THREAD

**Issue by codecShivam** [FOSS-Community/website-fossc#131]
Hello sir,
The resources page on the  website is currently under construction.  As a frequent visitor to the site, I would be happy to help with this and contribute to the creation of the page...

![Screenshot from 2023-04-23 20-16-52](https://user-images.githubusercontent.com/118369445/233846813-9b5e79fb-612e-4f66-9718-ea5041e9e835.png)

**Comment by Mr-Sunglasses** [comment]
Related to #116

**Comment by Mr-Sunglasses** [comment]
#151
