### ISSUE TITLE
Add a button to schedule doubt/queries session

### ISSUE THREAD

**Issue by akshatcoder-hash** [FOSS-Community/website-fossc#144]
### Describe the feature you'd like to request

Recently, we at FOSS Community proposed a new community structure. Based on that, the _'learners'_ can schedule time to discuss their queries and issues. We need a button on the website to schedule the session.

### Describe the solution you'd like

A button on the website to schedule the doubt/query resolution session.

### Describe alternatives you've considered

N/A

### Additional context

Link to schedule the session - https://cal.com/fosscu/

**Comment by Bharadwajshivam28** [comment]
@akshatcoder-hash creting a pr fixed it
