### ISSUE TITLE
Missing 'Resources' option/button on mobile view

### ISSUE THREAD

**Issue by anshika0987** [FOSS-Community/website-fossc#149]
### Contact Details

g.anshikacreative@gmail.com

### What happened?

<h3>I've noticed that the "Resources" button is missing from the mobile view of FOSSCU website. The button is present in the desktop view, but it is not present on the mobile version of the site. This makes it difficult to access important resources related to the project when using a mobile device.</h3>

<h3>@Mr-Sunglasses Sir, could you please assign this issue to me.</h3>

 
![fosscimage](https://user-images.githubusercontent.com/123721290/235305805-4c2b1986-1ff0-4f37-8b7a-ba4cc4191cde.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr-Sunglasses** [comment]
go ahead @anshika0987

**Comment by Mr-Sunglasses** [comment]
#150
