### ISSUE TITLE
[Bug]: Nav and Footer Components are Overlapping Each other in the resources page.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#155]
### Contact Details

itskanishkp.py@gmail.com

### What happened?

The footer and Nav components overlap the sidebar component of the Resource Section.

# REF to Images
![Screenshot 2023-05-03 at 1 38 40 AM](https://user-images.githubusercontent.com/81439109/235775409-8b080279-6485-4dac-b1d4-92a8af55789c.png)
![Screenshot 2023-05-03 at 1 38 51 AM](https://user-images.githubusercontent.com/81439109/235775636-dd44e13a-e673-4451-8417-25d7c8c4ea00.png)
![Screenshot 2023-05-03 at 1 39 14 AM](https://user-images.githubusercontent.com/81439109/235775644-3c3229a8-7ba5-4d4f-ade4-16001ac0a7f1.png)

The Optimal Approach is to Fix the nav and Footer components and then render the resource component b/w them, Looking Forward to Discussing more on this issue.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bharadwajshivam28** [comment]
> ### Contact Details
> 
> itskanishkp.py@gmail.com
> 
> ### What happened?
> 
> The footer and Nav components overlap the sidebar component of the Resource Section.
> 
> # REF to Images
> ![Screenshot 2023-05-03 at 1 38 40 AM](https://user-images.githubusercontent.com/81439109/235775409-8b080279-6485-4dac-b1d4-92a8af55789c.png)
> ![Screenshot 2023-05-03 at 1 38 51 AM](https://user-images.githubusercontent.com/81439109/235775636-dd44e13a-e673-4451-8417-25d7c8c4ea00.png)
> ![Screenshot 2023-05-03 at 1 39 14 AM](https://user-images.githubusercontent.com/81439109/235775644-3c3229a8-7ba5-4d4f-ade4-16001ac0a7f1.png)
> 
> The Optimal Approach is to Fix the nav and Footer components and then render the resource component b/w them, Looking Forward to Discussing more on this issue.
> 
> ### What browsers are you seeing the problem on?
> 
> Chrome
> 
> ### Relevant log output
> 
> _No response_
> 
> ### Code of Conduct
> 
> - [X] I agree to follow this project's Code of Conduct

Please assign to me sir i want to work on this

**Comment by codecShivam** [comment]
@Mr-Sunglasses sir ,  I have done some work on it so could you please assign this to me...

**Comment by codecShivam** [comment]
@Mr-Sunglasses  Thank you for reviewing my fix for this issue. Based on my testing and your feedback, I believe the issue has been resolved. Sir , could you please consider closing this issue now?
