### ISSUE TITLE
[Bug]: Improve the loading time for Fosscu Resource Pages for frontend https://fosscu.org/roadmap

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#157]
### Contact Details

itskanishkp.py@gmail.com

### What happened?

The current time to load the https://fosscu.org/roadmap page is very high. We need to reduce it.

# Stats

![Screenshot 2023-05-03 at 1 56 21 AM](https://user-images.githubusercontent.com/81439109/235781340-1216de05-a2ec-43e5-afb1-fe6e8ea34c9d.png)
![Screenshot 2023-05-03 at 2 02 01 AM](https://user-images.githubusercontent.com/81439109/235781348-ed8bedfe-f036-4504-a9bc-1c2f6685dd60.png)

# Problem and the Solution
I think the YouTube-embedded links have the problems as shown in the network tab logs under inspect section, so we need to find a good solution to load those YouTube videos in the resource page faster.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Request URL: https://static.doubleclick.net/instream/ad_status.js
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
Learn more
Referer: https://www.youtube.com/
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bharadwajshivam28** [comment]
@Mr-Sunglasses Can it done by using YouTube iframe api ??

**Comment by Rishika-0** [comment]
I would like to work on this issue, please assign it to me.

**Comment by Rishika-0** [comment]
@Mr-Sunglasses Please assign me this issue. I want to work on this.

**Comment by Rishika-993** [comment]
@Mr-Sunglasses #189
