### ISSUE TITLE
[Bug]:  Clicking on any option in the navbar in the Roadmap just scrolls to the top of the page.

### ISSUE THREAD

**Issue by SAMAD101** [FOSS-Community/website-fossc#159]
### Contact Details

asamadans@gmail.com

### What happened?

![Screenshot_20230503_145258](https://user-images.githubusercontent.com/71956678/235879185-02df8764-1dff-4833-906f-9e2aa03a05ab.png)

Clicking on any option in the navbar of Roadmap leads to the top of the page.

Expected behavior: It should scroll to he expected section of the page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codecShivam** [comment]
@Mr-Sunglasses sir,  I am working  on it so could you please  assign this issue to me.

**Comment by SAMAD101** [comment]
Whats the status?

**Comment by codecShivam** [comment]
> Whats the status?

Closing this issue as the content of the page has been updated in pr #189
