### ISSUE TITLE
[Bug]: Command not visible

### ISSUE THREAD

**Issue by Ahtaxam** [FOSS-Community/website-fossc#164]
### Contact Details

ahtaxam03@gmail.com

### What happened?

On Fosscu getting started page. command **Ctrl+k** is not visible to users.

![Screenshot from 2023-05-04 14-42-34](https://user-images.githubusercontent.com/64573767/236169864-f6985151-3998-48b8-89ba-3f186f029d04.png)

Note: I would like to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bharadwajshivam28** [comment]
@Ahtaxam the pull request of this issue have been already made

**Comment by Ahtaxam** [comment]
@Bharadwajshivam28 if pull request have been closed. then why changing are not visible ?

**Comment by Bharadwajshivam28** [comment]
pr have been made but not merged .. maintainer will come on and merge it

**Comment by Bharadwajshivam28** [comment]
https://github.com/FOSS-Community/Community-Hub/pull/10 

have a look
