### ISSUE TITLE
Implementing Calendar in the main page of Fosscu

### ISSUE THREAD

**Issue by Bharadwajshivam28** [FOSS-Community/website-fossc#169]
### Describe the feature you'd like to request

We need to add the fosscu calendar in the page

### Describe the solution you'd like

We have our Fosscu calendar but if someone wants to view it they have to search other links. So I have an idea to implement Calendar  button in Navbar which will redirect to the calendar page..

please assign to me i will share the demo @Mr-Sunglasses

**Comment by Bharadwajshivam28** [comment]
It can be like this or we can replace calendar with an calendar icon

https://user-images.githubusercontent.com/108119109/236528640-31a7fe43-7229-4cf1-8de0-1c2fe9df3ad1.mp4

**Comment by Mr-Sunglasses** [comment]
Thx @anshika0987
