### ISSUE TITLE
Add "what is FOSS" in footer under handbook column

### ISSUE THREAD

**Issue by Rishika-993** [FOSS-Community/website-fossc#185]
### Describe the feature you'd like to request

To discover the "What is FOSS" section which is currently present in the handbook page and contains the basic idea of FOSS and FOSSCU community and how it works, it is not directly accessible to the users.

### Describe the solution you'd like

Adding this section in the footer will provide more feasibility. 
(just like the other sections that are present over there)

### Additional context

#184 

@Mr-Sunglasses  review it

![Screenshot from 2023-05-27 00-49-59](https://github.com/FOSS-Community/website-fossc/assets/122405415/b03afaa0-e27f-48ef-962f-80a1c9c6bd1f)

**Comment by Mr-Sunglasses** [comment]
#184
