### ISSUE TITLE
Update the Metadata tags for the fosscu website.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#196]
Update the meta tags for the fosscu website, when we share the fosscu website, these meta tags help in the better preview of the website.

## Current Behaviour 
![Screenshot 2023-08-04 at 10 35 52 PM](https://github.com/FOSS-Community/website-fossc/assets/81439109/85c144d4-f106-43ab-81fe-f3826d1a335d)

## Expected Behaviour
Better Preview while sharing.

## Resources 

Website for Open-Graph-Protocol = https://ogp.me/
File to add these meta tags in the repo = https://github.com/FOSS-Community/website-fossc/blob/main/index.html

**Comment by irohanrajput** [comment]
I want to solve this, kindly assign this

**Comment by whit3st** [comment]
Happy to help, you can assign me.

**Comment by Mr-Sunglasses** [comment]
@whit3st @irohanrajput To avoid ambiguity, this issue is not assigned to anyone currently so is available to anyone. Submit a draft PR getting started on the work and we can assign it.

**Comment by irohanrajput** [comment]
Sure, on it
