### ISSUE TITLE
Site Social Preview: Add metadata and default image

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#2]
<h1> Goal </h1>
When posting a link on a social media sites (Twitter, Facebook, LinkedIn) there should be a nice preview image and title.

**Comment by Yash-Var** [comment]
@Mr-Sunglasses can you send the title and description ....

**Comment by Yash-Var** [comment]
Title : FOSSC Community
@Mr-Sunglasses

**Comment by GJS2162** [comment]
@Mr-Sunglasses I want to contribute to this . Could you assign this to me .

**Comment by Yash-Var** [comment]
@Mr-Sunglasses add meta tag of twitter review it ....
