### ISSUE TITLE
[Bug]: Github organization broken url.

### ISSUE THREAD

**Issue by antonio-pedro99** [FOSS-Community/website-fossc#222]
### What happened?

The link to access the FOSS-community from the conference website is wrong.
It should be `https://github.com/FOSS-Community` and not `https://github.com/foss-community`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vivekpal1** [comment]
https://github.com/FOSS-Community/fossconf/pull/22
