### ISSUE TITLE
[Feature] Adding a Light/Dark Theme toggle option.

### ISSUE THREAD

**Issue by Dhairya1Gupta** [FOSS-Community/website-fossc#234]
### Describe the feature you'd like to request

Hi sir I would like to add a Light/Dark Theme toggle option under Navigation Bar

### Describe the solution you'd like

I will add a toggle button which allows the user to switch between Light/Dark Mode in the website.

**Comment by A91y** [comment]
Hello @Dhairya1Gupta, Thank you for showing interest. But the site doesn't really need a Theme toggler.
So, you can propose any other related changes first to make it work.
