### ISSUE TITLE
[Bug]: One Team Member Link Broken

### ISSUE THREAD

**Issue by sarthak-stranger** [FOSS-Community/website-fossc#235]
### Contact Details

smartsarthakgupta12345@gmail.com

### What happened?

In Team Section Of Fosscu Community Website . The twitter Link of Shivam Yadav was not Working.

https://github.com/FOSS-Community/website-fossc/assets/92575432/8ac4cceb-97fc-4c79-ab57-4e27544b5d98

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarthak-stranger** [comment]
@codecShivam Please Assign this issue to me as i have resolved the same

**Comment by codecShivam** [comment]
go ahead!
