### ISSUE TITLE
[Feature] : Introduction to shipyard

### ISSUE THREAD

**Issue by codecShivam** [FOSS-Community/website-fossc#240]
### Describe the feature you'd like to request

Shipyard is the place to collaborate and ship dope stuff together.

### Describe the solution you'd like

Create a component/section highlighting the fosscu shipyard. Also include the details about the already shipped project

**Comment by JiyaGupta-cs** [comment]
@codecShivam I would like to work on this issue
Where can I get the details of the shipped products

**Comment by codecShivam** [comment]
> @codecShivam I would like to work on this issue Where can I get the details of the shipped products

Go ahead!

**Comment by codecShivam** [comment]
> @codecShivam I would like to work on this issue Where can I get the details of the shipped products

@piyusesh has already opened a pull request related to this issue, #241.

**Comment by codecShivam** [comment]
fixed in #241, thanks @piyusesh
