### ISSUE TITLE
Navbar Links are not working in Responsive mode or in Mobile Phone, Also fix the Navbar color in mobile mode. 😅

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#54]
![Screen Shot 2022-11-23 at 01 18 53](https://user-images.githubusercontent.com/81439109/203408070-828e1b1d-32c4-4bea-80e0-d96cb5e571f4.png)
<br>
![Screen Shot 2022-11-23 at 01 19 04](https://user-images.githubusercontent.com/81439109/203408079-a4274deb-b878-4466-9fdf-cf50d8f8aa8e.png)
<br>
![Screen Shot 2022-11-23 at 01 19 24](https://user-images.githubusercontent.com/81439109/203408097-27e29d21-79a7-4735-b891-b8fd0c8a3f9c.png)

Ref to file that need changes in [Navbar.jsx](https://github.com/FOSS-Community/website-fossc/blob/main/src/components/Navbar.jsx).

@Yash-Var - Try it if you can fix it or I'll do it myself 🫰🏻.

**Comment by Yash-Var** [comment]
@Mr-Sunglasses review it

**Comment by Mr-Sunglasses** [comment]
Done this issue is fixed now.
