### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by A91y** [FOSS-Community/website-fossc#71]
CONTRIBUTING.md and CODE_OF_CONDUCT.md can be added as a best practice.

**Comment by GitWiz01** [comment]
@ may I go for this issue ?

**Comment by A91y** [comment]
@GitWiz01 Thanks for asking, but I want to work on this issue as I opened it having plans in my brain.

**Comment by GitWiz01** [comment]
@A91y  ok buddy go for it

**Comment by Yash-Var** [comment]
@A91y you can proceed
