### ISSUE TITLE
Fixes in README.md required

### ISSUE THREAD

**Issue by A91y** [FOSS-Community/website-fossc#72]
Broken links need to be resolved or removed from README file for better experience.

**Comment by GitWiz01** [comment]
@A91y  Can I work on this ?

**Comment by A91y** [comment]
I have created plans on how to fix it, so I want to work on it as I opened the issue.

**Comment by GitWiz01** [comment]
@A91y can we collaborate

**Comment by A91y** [comment]
@GitWiz01 Is collaborating allowed in open source competitions ?

**Comment by GitWiz01** [comment]
Hi @Mr-Sunglasses 
can @A91y and I collaborate on this issue ?

**Comment by A91y** [comment]
@Mr-Sunglasses Please assign this issue to me, so that I can start working on it.

**Comment by GitWiz01** [comment]
@Mr-Sunglasses Can I work on this issue ?

**Comment by GitWiz01** [comment]
@Mr-Sunglasses please assign this issue. So I can make a pr

**Comment by Yash-Var** [comment]
@GitWiz01 you can proceed

**Comment by A91y** [comment]
@Yash-Var I raised the issue and started working, why you assigned it to some one else.

**Comment by Yash-Var** [comment]
@A91y no problem you can also work on that I will assign it to you

**Comment by RyanWalker277** [comment]
> @A91y no problem you can also work on that I will assign it to you

@Yash-Var Don't assign two people the same issue. If someone has asked to assign the issue to him first, assign him the issue. If he is unable to do it then you can remove the assignment and assign it to someone else.

@Mr-Sunglasses Please look into it.
