### ISSUE TITLE
Fix the Link of Blog in navbar

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#73]
The current hyperlink of Blog in Navbar does not redirect to fosscu-blog. We need to redirect it to fosscu-blog.vercel.app.

**Comment by GitWiz01** [comment]
@Mr-Sunglasses please assign me this issue under Iwoc'23

**Comment by Mr-Sunglasses** [comment]
@GitWiz01 Sure go ahead ....

**Comment by shyamtawli** [comment]
@Mr-Sunglasses Sorry I didn't see that it is assigned. Should I delete it ?

**Comment by Mr-Sunglasses** [comment]
Solved in #74
