### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by GJS2162** [FOSS-Community/website-fossc#8]
**Create a file CodeOfConduct.md and write the guidelines for contributing.**

Includes : 
At the time of filing PR 
- [x] I have read the Code Of Conduct
- [x] I have read the README.md file.

**Comment by Yash-Var** [comment]
@GJS2162 I want to work on this .......

**Comment by Mr-Sunglasses** [comment]
@GJS2162 I think all the TO-DO are completed for this issue so its the right time to close it.
