### ISSUE TITLE
Fix the navbar links and add issue and pull request templates.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#84]
# fixed the Links in the navbar

<img width="1440" alt="Screenshot 2023-02-25 at 6 54 48 PM" src="https://user-images.githubusercontent.com/81439109/221359646-62bb3f50-b68f-46ce-a743-34d474366a37.png">

# Add Issue template and Pull request template.

**Comment by Bharadwajshivam28** [comment]
assign to me sir @Mr-Sunglasses
