### ISSUE TITLE
Add steps to run through docker.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#89]
Add the steps the run the website with docker using dockerfile.

**Comment by Bharadwajshivam28** [comment]
> Add the steps the run the website with docker using dockerfile.

@Mr-Sunglasses Please assign to me sir i want to complete this

**Comment by Mr-Sunglasses** [comment]
Fixed <br> ![its fixed](https://media.tenor.com/WlD9-QFAB6MAAAAC/fixed.gif)
