### ISSUE TITLE
add social media and other contact links into contacts page.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#90]
### Currently the contact page has only a contact form but if someone wants to reach us through mail or other social media platforms we need to look after that so it's better to add those to the website.

**Comment by Bharadwajshivam28** [comment]
> # Currently the contact page has only a contact form but if someone wants to reach us through mail or other social media platforms we need to look after that so it's better to add those to the website.

I want to work on it sir please assign to me

**Comment by Mr-Sunglasses** [comment]
@Bharadwajshivam28 We can only assign you to a single issue, complete that issue first then we'll assign you to this issue. I'll help us to allow new people who are coming here to solve new issues.

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 We can only assign you to a single issue, complete that issue first then we'll assign you to this issue. It'll help us to allow new people who are coming here to solve new issues.

Okay sir

**Comment by Mr-Sunglasses** [comment]
#110
