### ISSUE TITLE
Migrate from create-react-app to vite.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/website-fossc#92]
The current portal uses create-react-app which is obsolete and doesn't recommend by the react team due to its speed issues. Vite is a good alternative so migrate the website to Vite.

**Comment by codecShivam** [comment]
Sir, could you please assign me this issue? I'd love to take on the challenge and help with the migration process...

**Comment by Mr-Sunglasses** [comment]
for reference read this article 😄 : https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite

**Comment by Bharadwajshivam28** [comment]
> for reference read this article 😄 : https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite

Can I work on it ?

**Comment by Mr-Sunglasses** [comment]
@Bharadwajshivam28 please solve the previous assigned issues.

**Comment by Mr-Sunglasses** [comment]
Done on #100 , Thanks @codecShivam 🙌🏻
