### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Bharadwajshivam28** [FOSS-Community/website-fossc#94]
When we head  to the Team section then the profile link of one Person is broken.

![Screenshot from 2023-04-03 00-21-48](https://user-images.githubusercontent.com/108119109/229372978-62e654d9-3889-4d50-97c8-ad985021cc57.png)

**Comment by Bharadwajshivam28** [comment]
Creating a Pull Request by fixing it

**Comment by Mr-Sunglasses** [comment]
#96 Fixed by this PR.
